### ISSUE TITLE
Project View Your Users Will Like :) -- Smoother Project Transition

### ISSUE THREAD

**Issue by leehorthung** [nserguier/IdeasTracker#5]
Hey IdeasTracker team :)

Think you'll like this idea.

I've noticed that anytime I switch between projects, the project info / settings (on the left) keep opening up. It makes it tough for users to easily search through tasks between projects. 

Your users will like it much better if you set the projects' settings as collapsed **by** default. 

If there is something I'm missing from your design, sorry to have suggested wrongly!

Hoping for your success with a great app! :)

**Comment by nserguier** [comment]
Hi @leehorthung!

Thanks a lot for sharing about this :) I'll look into that issue but I believe this is not an intended behavior, good catch. I'll fix it later today and submit a quick update to the app.

Thanks again, looking forward to hear more suggestions!

**Comment by nserguier** [comment]
Hey @leehorthung, I just updated the app to close the drawer when switching between projects. It should be out on the store in a few hours.

By the way, did you know that when you are on the main page (drawers are closed), you can click on the project's name in the toolbar to show a small menu and quickly switch between projects! Enjoy :)
